### ISSUE TITLE
README could mention a more compatible run command for Windows: 'npx love.js.cmd'

### ISSUE THREAD

**Issue by IoriBranford** [Davidobot/love.js#48]
On Windows cmd and Powershell, I can run love.js only with `npx love.js.cmd`, not `npx love.js` which tries to run the Unix shell script instead of the cmd or Powershell ones:

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

Maybe this has something to do with my Node.js installation (installed LTS with winget, and associated js files with node.exe) but even so, it's worth mentioning in the readme.

**Comment by thelazyone** [comment]
Running the command on Windows and with PowerShell I am not finding issues with `npx love.js`, while if calling `npx love.js.cmd` i'm getting a 404: _npm ERR! 404 Not Found - GET https://registry.npmjs.org/love.js.com - Not found_
