### ISSUE TITLE
The build procedure is inconsistent in windows and linux scripts

### ISSUE THREAD

**Issue by ParticleG** [Davidobot/love.js#98]
I've forked the repo and made a github action workflow for it: [main.yml](https://github.com/26F-Studio/love.js/blob/master/.github/workflows/main.yml)

And I noticed the cmake parameters are different in [`build_lovejs.bat`](https://github.com/26F-Studio/love.js/blob/031e5ea7132dbe28c7619cffb927df79ea8caee3/build_lovejs.bat#L21) and [`build_lovejs.sh`](https://github.com/26F-Studio/love.js/blob/031e5ea7132dbe28c7619cffb927df79ea8caee3/build_lovejs.sh#L33) , I use linux script for reference and successfully built a compat version [release](https://github.com/26F-Studio/love.js/actions/runs/11600799920)

I also noticed the release version failed to built due to `--shared-memory` [issue](https://github.com/26F-Studio/love.js/actions/runs/11600799920/job/32302086432#step:6:2948)

Could you please take a look and help me fix the build procedure?

**Comment by ParticleG** [comment]
Also the compat version can't launch the game due to:
```log
Uncaught TypeError: Module.getMemory is not a function
    at processPackageData (game.js:230:38)
    at putMetadataRequest.onsuccess (game.js:209:11)
```
![image](https://github.com/user-attachments/assets/56cee494-69fc-4ce6-8e53-d81e35d738e9)

**Comment by ParticleG** [comment]
Figured it out. It's due to using a newer version of emsdk
